name: Build and Deploy # 工作流的名称
on: # 触发条件：当代码推送到main分支时启动
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新的Ubuntu系统作为构建环境
    steps:
      # 1. 获取你的项目代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 安装Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 推荐使用Node.js 18或更高版本

      # 3. 安装依赖并构建网站
      - name: Install and Build
        run: |
          npm install
          npm run build:win # 执行构建，生成静态文件
          touch docs/.vuepress/dist/.nojekyll

      # 4. 部署到GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 部署到的目标分支
          folder: docs/.vuepress/dist # VuePress构建后的静态文件目录
          token: ${{ secrets.ACCESS_TOKEN }} # 使用你之前设置的密钥
